-- TABLAS DEL SISTEMA HUELLAS SEGURAS

CREATE TABLE ANIMALES (
    ID_ANIMAL     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE        VARCHAR2(100) NOT NULL,
    ESPECIE       VARCHAR2(50)  NOT NULL,
    RAZA          VARCHAR2(100),
    FECHA_ENTRADA DATE          NOT NULL,
    ESTADO        VARCHAR2(20)  NOT NULL,
    CONSTRAINT chk_estado CHECK (ESTADO IN ('Disponible', 'En tratamiento', 'Adoptado'))
);

CREATE TABLE ADOPTANTES (
    ID_ADOPTANTE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE       VARCHAR2(150) NOT NULL,
    DNI          VARCHAR2(20)  NOT NULL,
    EMAIL        VARCHAR2(200) NOT NULL,
    TELEFONO     VARCHAR2(20),
    CONSTRAINT uq_dni   UNIQUE (DNI),
    CONSTRAINT uq_email UNIQUE (EMAIL)
);

CREATE TABLE ADOPCIONES (
    ID_ADOPCION   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ANIMAL     NUMBER NOT NULL,
    ID_ADOPTANTE  NUMBER NOT NULL,
    FECHA         DATE   NOT NULL,
    OBSERVACIONES VARCHAR2(500),
    CONSTRAINT fk_adop_animal    FOREIGN KEY (ID_ANIMAL)    REFERENCES ANIMALES(ID_ANIMAL),
    CONSTRAINT fk_adop_adoptante FOREIGN KEY (ID_ADOPTANTE) REFERENCES ADOPTANTES(ID_ADOPTANTE)
);

CREATE TABLE HISTORIAL_MEDICO (
    ID_HISTORIAL NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ANIMAL    NUMBER         NOT NULL,
    FECHA        DATE           NOT NULL,
    DESCRIPCION  VARCHAR2(1000) NOT NULL,
    COSTE        NUMBER(10,2),
    CONSTRAINT fk_hist_animal FOREIGN KEY (ID_ANIMAL) REFERENCES ANIMALES(ID_ANIMAL)
);

CREATE TABLE LOG_CAMBIOS_ANIMAL (
    ID_LOG          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ANIMAL       NUMBER        NOT NULL,
    ESTADO_ANTERIOR VARCHAR2(20),
    ESTADO_NUEVO    VARCHAR2(20)  NOT NULL,
    FECHA_CAMBIO    DATE          NOT NULL,
    USUARIO_BD      VARCHAR2(100) NOT NULL
);